Prototype/config/routes.rb
Rails.application.routes.draw do
	root "sessions#new"
	resources :subsystem_tbls do
		post :check_unique, on: :collection
		match :search, to: 'subsystem_tbls#index', via: :post, on: :collection
	end	
	resources :ui_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'ui_types_tbls#index', via: :post, on: :collection
	end
	resources :cmd_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'cmd_types_tbls#index', via: :post, on: :collection
	end
	resources :confirmation_type_tbls do
		match :search, to: 'confirmation_type_tbls#index', via: :post, on: :collection
	end
	resources :expressions do
		post :check_unique, on: :collection
		match :search, to: 'expressions#index', via: :post, on: :collection
	end
	resources :cmd_part_types_tbls do
		match :search, to: 'cmd_part_types_tbls#index', via: :post, on: :collection
	end
		
	resources :base_cmd_tbls do
		post :sub_short_name, on: :collection
		post :check_unique, on: :collection
		match :search, to: 'base_cmd_tbls#index', via: [:get, :post], on: :collection
	end
	resources :cmd_part_tbls do
		post :check_unique, on: :collection
	end
	resources :prereq_conf_expr_tbls do
		post :check_unique, on: :collection
	end
	resources :cpid_tbls do
		post :check_unique, on: :collection
	end

	resources :bit_sel_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'bit_sel_tbl_infos#index', via: :post, on: :collection
	end
	resources :bit_sel_tbls do
		post :check_unique, on: :collection
	end
	
	resources :lkup_tbls do
		post :check_unique, on: :collection
	end
	resources :lkup_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'lkup_tbl_infos#index', via: :post, on: :collection
	end
	
	resources :users
	resources :satellite_tables
	
	resources :sessions, only: [:new, :create, :destroy] do
		post :get_db_details, on: :collection

	end
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout',  to: 'sessions#destroy'
	get  '/signup',  to: 'users#new'
  	post '/signup',  to: 'users#create'

  	get '/versions', to: "versions#index"
  	resources :versions, only: :destroy

  	resources :base_formation_logic_tbls
  	resources :map_id_tbls
  	resources :part_type_tbls
  	resources :input_format_tbls
  	resources :preferrable_decoder_tbls
  	resources :criticality_tbls
  	resources :pulse_width_tbls
  	resources :lkup_tbl_type_tbls
  	resources :logical_op_tbls

  	resources :entry_type_tbls
  	resources :value_type_tbls
  	resources :rel_op_tbls
  	resources :form_logic_part_type_tbls
  	resources :formation_logic_tbls
  	resources :form_logic_part_data_tbls do
  		post :check_unique, on: :collection
  		post :fetch_sub_logic_val, on: :collection
 	end
  	resources :expr_type_tbls
  	
end

Prototype/app/models/cmd_part_types_tbl.rb
class CMD_PART_TYPES_TBL < AllConfigAccess
	self.table_name = "CMD_PART_TYPES_TBL"
	has_paper_trail class_name: 'Version'

	validates :CMD_PART_TYPE_ID, presence: true, uniqueness: true
    validates :CMD_PART_TYPE, presence: true, length: { maximum: 32 }, uniqueness: true
end

Prototype/app/controllers/cmd_part_types_tbls_controller.rb
class CmdPartTypesTblsController < ParentController
	before_action :admin_user, except: :index
	before_action :set_base_cmd_session_to_nil

	def index
		@search = CMD_PART_TYPES_TBL.ransack(params[:q])
		@cmd_part_types = @search.result
		@search.build_condition
	end

	def new
		@cmd_part_types = CMD_PART_TYPES_TBL.new
	end

	def show
		@cmd_part_types = CMD_PART_TYPES_TBL.find(params[:id])
	end

	def edit
		@cmd_part_types = CMD_PART_TYPES_TBL.find(params[:id])
	end

	def create
		@cmd_part_types = CMD_PART_TYPES_TBL.new(cmd_part_type_params)
		if @cmd_part_types.save
			flash[:success] = "Successfully created cmd part type #{@cmd_part_types.CMD_PART_TYPE}"
			redirect_to @cmd_part_types
		else
			render 'new'
		end
	end

	def update
		@cmd_part_types = CMD_PART_TYPES_TBL.find(params[:id])
		if @cmd_part_types.update_attributes(cmd_part_type_params)
			flash[:success] = "Successfully updated cmd part type #{@cmd_part_types.CMD_PART_TYPE}"
			redirect_to cmd_part_types_tbls_url
		else
			render 'edit'
		end
	end

	def destroy
		@cmd_part_types = CMD_PART_TYPES_TBL.find(params[:id])
		@cmd_part_types.destroy
		flash[:warning] = "Successfully deleted cmd part type #{@cmd_part_types.CMD_PART_TYPE}"
		redirect_to cmd_part_types_tbls_url
	end

	private

		def cmd_part_type_params
			params.require(:cmd_part_types_tbl).permit(:CMD_PART_TYPE)
		end
end

Prototype/app/helpers/cmd_part_types_tbls_helper.rb
module CmdPartTypesTblsHelper
end

Prototype/app/views/cmd_part_types_tbls/_condition_fields.html.erb
<div class="field">
  <div class="search_field">
    <%= f.attribute_fields do |a| %>
      <%= a.attribute_select class: "radius" %>
    <% end %>
  </div>
  <div class="search_field">
    <%= f.predicate_select Hash.new, class: "radius" %>
  </div>
  <div class="insert_field">
    <%= f.value_fields do |v| %>
      <%= v.text_field :value, class: "radius search_input", placeholder: 'Search Input' %>
    <% end %>
    <p class="remove_fields"><%= link_to "Remove", "", class: "remove_fields" %></p>
  </div>
</div>

Prototype/app/views/cmd_part_types_tbls/edit.html.erb
<h1>EDIT CMD_PART_TYPES_TBL </h1>
<div class="perfect-forms">

<%= form_for(@cmd_part_types) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	
	<div class="form-row">  
	  <%= f.label :CMD_PART_TYPE %>
	  <%= f.text_field :CMD_PART_TYPE, class: 'form-control' %>
	</div>
	
	<div class="form-row"> 
	  <%= f.submit 'Update', class: "btn btn-primary" %>
	</div>
	  
<% end %>
</div>

Prototype/app/views/cmd_part_types_tbls/index.html.erb
<div class="table-view">
	<table>
		<caption>LIST OF CMD_PART_TYPES</caption>
		<thead>
			<tr>
				<th> CMD_PART_TYPE_ID</th>
				<th> CMD_PART_TYPE </th>

			</tr>
		</thead>
<tbody>

<% @cmd_part_types.each do |f| %>
	<tr data-href="<%= edit_cmd_part_types_tbl_path(f) %>" class="theShower text-center">
		
			<td><%=f.CMD_PART_TYPE_ID%></td>
			<td><%=f.CMD_PART_TYPE%></td>
			<% if current_user.admin? %>	<!-- add this too -->
					<td class="deleter"><%= link_to "x", f , method: :delete, data: { confirm: "You sure?" } %></td>	<!-- add this too -->
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
	</div>
<div class="lower-options add_to_right">
	<%= link_to 'Add', new_cmd_part_types_tbl_path, class: "add-new-table" %>
</div>

Prototype/app/views/cmd_part_types_tbls/new.html.erb
<h1>CREATE CMD_PART_TYPES_TBL </h1>
<div class="perfect-forms">

<%= form_for(@cmd_part_types) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<div class="form-row">  
	  <%= f.label :CMD_PART_TYPE %>
	  <%= f.text_field :CMD_PART_TYPE, class: 'form-control' %>
	</div>
	
	<div class="form-row"> 
	  <%= f.submit 'Create', class: "btn btn-primary" %>
	</div>
	  
<% end %>
</div>