Prototype/config/routes.rb
Rails.application.routes.draw do
	root "sessions#new"
	resources :subsystem_tbls do
		post :check_unique, on: :collection
		match :search, to: 'subsystem_tbls#index', via: :post, on: :collection
	end	
	resources :ui_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'ui_types_tbls#index', via: :post, on: :collection
	end
	resources :cmd_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'cmd_types_tbls#index', via: :post, on: :collection
	end
	resources :confirmation_type_tbls do
		match :search, to: 'confirmation_type_tbls#index', via: :post, on: :collection
	end
	resources :expressions do
		post :check_unique, on: :collection
		match :search, to: 'expressions#index', via: :post, on: :collection
	end
	resources :cmd_part_types_tbls do
		match :search, to: 'cmd_part_types_tbls#index', via: :post, on: :collection
	end
		
	resources :base_cmd_tbls do
		post :sub_short_name, on: :collection
		post :check_unique, on: :collection
		match :search, to: 'base_cmd_tbls#index', via: [:get, :post], on: :collection
	end
	resources :cmd_part_tbls do
		post :check_unique, on: :collection
	end
	resources :prereq_conf_expr_tbls do
		post :check_unique, on: :collection
	end
	resources :cpid_tbls do
		post :check_unique, on: :collection
	end

	resources :bit_sel_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'bit_sel_tbl_infos#index', via: :post, on: :collection
	end
	resources :bit_sel_tbls do
		post :check_unique, on: :collection
	end
	
	resources :lkup_tbls do
		post :check_unique, on: :collection
	end
	resources :lkup_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'lkup_tbl_infos#index', via: :post, on: :collection
	end
	
	resources :users
	resources :satellite_tables
	
	resources :sessions, only: [:new, :create, :destroy] do
		post :get_db_details, on: :collection

	end
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout',  to: 'sessions#destroy'
	get  '/signup',  to: 'users#new'
  	post '/signup',  to: 'users#create'

  	get '/versions', to: "versions#index"
  	resources :versions, only: :destroy

  	resources :base_formation_logic_tbls
  	resources :map_id_tbls
  	resources :part_type_tbls
  	resources :input_format_tbls
  	resources :preferrable_decoder_tbls
  	resources :criticality_tbls
  	resources :pulse_width_tbls
  	resources :lkup_tbl_type_tbls
  	resources :logical_op_tbls

  	resources :entry_type_tbls
  	resources :value_type_tbls
  	resources :rel_op_tbls
  	resources :form_logic_part_type_tbls
  	resources :formation_logic_tbls
  	resources :form_logic_part_data_tbls do
  		post :check_unique, on: :collection
  		post :fetch_sub_logic_val, on: :collection
 	end
  	resources :expr_type_tbls
  	
end

Prototype/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Prototype/app/views/shared/_option_list.html.erb
<div class="options_bar">

	<% if controller_name == 'base_cmd_tbls' && action_name == 'edit' %>

		<div class="btn-group btn-group-sm">

			<%= link_to "PREREQ CONF", prereq_conf_expr_tbls_path, class: "btn btn-info" %>
			<%=link_to "+", new_prereq_conf_expr_tbl_path, class: "btn btn-info" %>

  		</div>


  		<div class="btn-group btn-group-sm">

			<%= link_to "CMD PART", cmd_part_tbls_path, class: "btn btn-info" %>
			<%=link_to "+", new_cmd_part_tbl_path, class: "btn btn-info" %>

  		</div>


  		<div class="btn-group btn-group-sm">

			<%= link_to "CPID", cpid_tbls_path, class: "btn btn-info" %>
			<%=link_to "+", new_cpid_tbl_path, class: "btn btn-info" %>

  		</div>

		<div class="btn-group btn-group-sm">

			<%= link_to "FORM DATA", form_logic_part_data_tbls_path, class: "btn btn-info" %>
			<%=link_to "+", new_form_logic_part_data_tbl_path, class: "btn btn-info" %>

  		</div>  		
  
	<% elsif controller_name == 'bit_sel_tbl_infos' && action_name == 'edit' %>

		<div class="btn-group btn-group-sm">

			<%= link_to "BIT SEL TABLE", bit_sel_tbls_path(bits: @bit_infos), class: "btn btn-info" %>
			<%=link_to "+", new_bit_sel_tbl_path, class: "btn btn-info" %>

		</div>
			
	<% elsif controller_name == 'lkup_tbl_infos' && action_name == 'edit' %>
		
		<div class="btn-group btn-group-sm">

			<%= link_to "LKUP TABLE", lkup_tbls_path, class: "btn btn-info" %>
			<%=link_to "+", new_lkup_tbl_path, class: "btn btn-info" %>

		</div>
	        
	<% end %>
	
</div>

Prototype/app/views/shared/_search_list.html.erb
<div>
	<% if controller_name == 'base_cmd_tbls' && action_name == 'index' %>
    <div class="ForMainSearch">
      <p><strong>Sort By Fields</strong></p>
      <%= form_tag base_cmd_tbls_path, :method => 'get' do %>
        <div id="divSelector">
          <%= select_tag :column, options_for_select(["SUBSYSTEM","UI_TYPE","CMD_TYPE"]), :prompt => "Please select",class: 'form-control column_selector'%>
        </div>
        <div id='subsystem'>
          <%= select_tag :column_entry, options_from_collection_for_select(SUBSYSTEM_TBL.all, :SUBSYSTEM_NAME, :SUBSYSTEM_NAME), :prompt => "Please select",class: 'form-control'%>
        </div>
        <div id='ui_type'>
          <%= select_tag :column_entry, options_from_collection_for_select(UI_TYPES_TBL.all, :UI_TYPE, :UI_TYPE), :prompt => "Please select",class: 'form-control'%>
        </div>
        <div id='cmd_type'>
          <%= select_tag :column_entry, options_from_collection_for_select(CMD_TYPES_TBL.all, :CMD_TYPE, :CMD_TYPE), :prompt => "Please select",class: 'form-control'%>
        </div>
        <%= submit_tag "SORT", :name => "Sort", class: "sortersubmit search_input"%>
      <% end %>
    </div>

      <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", base_cmd_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
        <%= search_form_for @search, url: search_base_cmd_tbls_path, method: :post, class: 'ransack-form' do |f| %>
          <%= hidden_field_tag 'page', '1', {class: 'ransack-page'} %>  <!-- for ransack paginate with post method -->
          <%= hidden_field_tag 'ransack_true', true %> <!-- for ransack paginate with post method -->
          <%= f.condition_fields do |c| %>

            <%= render "condition_fields", f: c %>
          <% end %>
          <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
          <%= f.submit "Search", :name => "Base", class: "search_input"%>
        <% end %>
      </div>

      <div><hr size= "20"></div>

      <div id="ForBitSel">
        <p><strong>From Bit-Sel Name</strong></p>
        <%= form_tag base_cmd_tbls_path, :method => 'get' do %>
          <div>
            <%= select_tag :BitSelTblName, options_from_collection_for_select(BIT_SEL_TBL_INFO.all, :BIT_SEL_TBL_NAME, :BIT_SEL_TBL_NAME, params[:BitSelTblName]), :prompt => "Please select",class: 'form-control'%>
            <%= submit_tag "Search", :name => "BitSel", class: "search_input" %>
          </div>
        <% end %>
      </div>

      <div><hr/></div>

      <div id="ForLkup">
        <p><strong>From Lkup Name</strong></p>
        <%= form_tag base_cmd_tbls_path, :method => 'get' do %>
          <div>
            <%= select_tag :LkupTblName, options_from_collection_for_select(LKUP_TBL_INFO.all, :LKUP_TBL_NAME, :LKUP_TBL_NAME, params[:LkupTblName]), :prompt => "Please select",class: 'form-control'%>
            <%= submit_tag "Search", :name => "Lkup", class: "search_input"%>
          </div>
        <% end %>
      </div> 



	<% elsif controller_name == 'subsystem_tbls' && action_name == 'index' %>	

      <div class="ForMainSearch">
        <p><strong>Clear Search</strong></p>
        <%= link_to "CLEAR", subsystem_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>

      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
        <%= search_form_for @search do |f| %>
          <%= f.condition_fields do |c| %>
            <%= render "condition_fields", f: c %>
          <% end %> 
          <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
          <%= f.submit "Search", class: "search_input"%>
        <% end %>
      </div>


 <% elsif controller_name == 'ui_types_tbls' && action_name == 'index' %>

      <div class="ForMainSearch">
        <p><strong>Clear Search</strong></p>
        <%= link_to "CLEAR", ui_types_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>

      <div class="ForMainSearch">
        
        <p><strong>Choose Required Fields</strong></p>
        <%= search_form_for @search, url: search_ui_types_tbls_path, method: :post do |f| %>
          <%= f.condition_fields do |c| %>
            <%= render "condition_fields", f: c %>
          <% end %>
        <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
          <%= f.submit "Search", class: "search_input"%>
        
        <% end %>
      
      </div>

 
  <% elsif controller_name == 'cmd_types_tbls' && action_name == 'index' %>

      <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", cmd_types_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_cmd_types_tbls_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      
      
      <% end %>
   
    </div>

 
  <% elsif controller_name == 'cmd_part_types_tbls' && action_name == 'index' %>
    
    <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", cmd_part_types_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_cmd_part_types_tbls_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      
      <% end %>
    
    </div>  

  <% elsif controller_name == 'lkup_tbl_infos' && action_name == 'index' %>
    
    <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", lkup_tbl_infos_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_lkup_tbl_infos_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      
      
      <% end %>
    </div>

  <% elsif controller_name == 'bit_sel_tbl_infos' && action_name == 'index' %>
    
    <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", bit_sel_tbl_infos_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_bit_sel_tbl_infos_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      
      
      <% end %>
    </div>

    <% elsif controller_name == 'confirmer_tbls' && action_name == 'index' %>
    
    <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", confirmer_tbls_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_confirmer_tbls_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      
      <% end %>
    </div>

  <% elsif controller_name == 'expressions' && action_name == 'index' %>
    
    <div class="ForMainSearch">
        <p><strong>Clear Search And Sort</strong></p>
        <%= link_to "CLEAR", expressions_path, class: "btn btn-danger btn-xs" %>
      </div>
     
      <div><hr/></div>
      
      <div class="ForMainSearch">
        <p><strong>Choose Required Fields</strong></p>
      
      <%= search_form_for @search, url: search_expressions_path, method: :post do |f| %>
        <%= f.condition_fields do |c| %>
          <%= render "condition_fields", f: c %>
        <% end %>
      <p class="add_fields"><%= link_to_add_fields "Add Conditions", f, :condition %></p>
        <%= f.submit "Search", class: "search_input"%>
      <% end %>
    
    </div>
  
  <% end %>


</div>

Prototype/app/views/shared/_table_list.html.erb
<div class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Tables List <b class="caret"></b></a>
  <ul class="dropdown-menu">
        
    <li><%= link_to "Cmd Types", cmd_types_tbls_path %></li>
    <li><%= link_to "Subsystem", subsystem_tbls_path %></li>
    <li><%= link_to "Base Cmd", base_cmd_tbls_path %></li>
    <li><%= link_to "UI Types", ui_types_tbls_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Form Logic Data", form_logic_part_data_tbls_path(val: "1") %></li>
    <li><%= link_to "Prereq Conf", prereq_conf_expr_tbls_path(val: "1") %></li>
    <li><%= link_to "Cmd Part", cmd_part_tbls_path(val: "1") %></li>
    <li><%= link_to "Cpid", cpid_tbls_path(val: "1") %></li>
    <li><%= link_to "Expressions", expressions_path %></li>
    <li><%= link_to "Bit Sel Info", bit_sel_tbl_infos_path %></li>
    <li><%= link_to "Lkup Info", lkup_tbl_infos_path %></li>
    <li><%= link_to "Bit Sels", bit_sel_tbls_path(val: "1") %></li>
    <li><%= link_to "Lkups", lkup_tbls_path(val: "1") %></li>
    <% if current_user.modifiability? %>
        <li class="divider"></li>
        <li><%= link_to "Base Form Logic", base_formation_logic_tbls_path %></li>
        <li><%= link_to "Formation Logic", formation_logic_tbls_path %></li>
        <li><%= link_to "Form Logic Part", form_logic_part_type_tbls_path %></li>
        <li><%= link_to "Cmd Part Type", cmd_part_types_tbls_path %></li>
        <li><%= link_to "Pref Decoders", preferrable_decoder_tbls_path %></li>
        <li><%= link_to "Confirmation", confirmation_type_tbls_path %></li>
        <li><%= link_to "Input Format", input_format_tbls_path %></li>
        <li><%= link_to "Pulse Width", pulse_width_tbls_path %></li>
        <li><%= link_to "Value Type", value_type_tbls_path %></li>
        <li><%= link_to "Entry Type", entry_type_tbls_path %></li>
        <li><%= link_to "Logical OP", logical_op_tbls_path %></li>
        <li><%= link_to "Lkup Type", lkup_tbl_type_tbls_path %></li>
        <li><%= link_to "Expr Type", expr_type_tbls_path %></li>
        <li><%= link_to "Criticality", criticality_tbls_path %></li>
        <li><%= link_to "Rel OP", rel_op_tbls_path %></li>
        <li><%= link_to "Map ID", map_id_tbls_path %></li>
    <% end %>
  </ul>
</div>