Prototype/config/routes.rb
Rails.application.routes.draw do
	root "sessions#new"
	resources :subsystem_tbls do
		post :check_unique, on: :collection
		match :search, to: 'subsystem_tbls#index', via: :post, on: :collection
	end	
	resources :ui_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'ui_types_tbls#index', via: :post, on: :collection
	end
	resources :cmd_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'cmd_types_tbls#index', via: :post, on: :collection
	end
	resources :confirmation_type_tbls do
		match :search, to: 'confirmation_type_tbls#index', via: :post, on: :collection
	end
	resources :expressions do
		post :check_unique, on: :collection
		match :search, to: 'expressions#index', via: :post, on: :collection
	end
	resources :cmd_part_types_tbls do
		match :search, to: 'cmd_part_types_tbls#index', via: :post, on: :collection
	end
		
	resources :base_cmd_tbls do
		post :sub_short_name, on: :collection
		post :check_unique, on: :collection
		match :search, to: 'base_cmd_tbls#index', via: [:get, :post], on: :collection
	end
	resources :cmd_part_tbls do
		post :check_unique, on: :collection
	end
	resources :prereq_conf_expr_tbls do
		post :check_unique, on: :collection
	end
	resources :cpid_tbls do
		post :check_unique, on: :collection
	end

	resources :bit_sel_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'bit_sel_tbl_infos#index', via: :post, on: :collection
	end
	resources :bit_sel_tbls do
		post :check_unique, on: :collection
	end
	
	resources :lkup_tbls do
		post :check_unique, on: :collection
	end
	resources :lkup_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'lkup_tbl_infos#index', via: :post, on: :collection
	end
	
	resources :users
	resources :satellite_tables
	
	resources :sessions, only: [:new, :create, :destroy] do
		post :get_db_details, on: :collection

	end
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout',  to: 'sessions#destroy'
	get  '/signup',  to: 'users#new'
  	post '/signup',  to: 'users#create'

  	get '/versions', to: "versions#index"
  	resources :versions, only: :destroy

  	resources :base_formation_logic_tbls
  	resources :map_id_tbls
  	resources :part_type_tbls
  	resources :input_format_tbls
  	resources :preferrable_decoder_tbls
  	resources :criticality_tbls
  	resources :pulse_width_tbls
  	resources :lkup_tbl_type_tbls
  	resources :logical_op_tbls

  	resources :entry_type_tbls
  	resources :value_type_tbls
  	resources :rel_op_tbls
  	resources :form_logic_part_type_tbls
  	resources :formation_logic_tbls
  	resources :form_logic_part_data_tbls do
  		post :check_unique, on: :collection
  		post :fetch_sub_logic_val, on: :collection
 	end
  	resources :expr_type_tbls
  	
end

Prototype/app/views/layouts/partials/_flash.html.erb
<div class="flash">
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
</div>

Prototype/app/views/layouts/partials/_footer.html.erb
<footer class="footer">
	<em>Best Viewed in Mozilla Firefox v55 and above</em><bot> &copy: ISRO 2018 </bot>
	<em style="float: right;color: orange;font-weight: 900;"> Press F11 </em>
</footer>

Prototype/app/views/layouts/partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-brand">
      <%= image_tag("isro-logo-mini.png", alt: "logo", class: "logo_image")%>
      <%= link_to "ISRO", base_cmd_tbls_path , id: "logo" %>
    </div>
    <div class="navbar-collapse collapse">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Home", base_cmd_tbls_path %></li>
              <li><%= link_to "Track Changes", versions_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <% if  current_user.admin? %>   
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Satellites", satellite_tables_path %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                 </ul>
                </li>
              <% else %>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>  
              <% end %>            
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
      </nav>
    </div>  
</header>

Prototype/app/views/layouts/partials/_nav.html.erb
<!-- <p class="nav_arrow"><span class="left_arrow"><i class="left"></i></span><span class="right_arrow"><i class="right"></i></span></p> -->
<p class="nav_arrow"><span class="left_arrow btn btn-xs">&#8678;</span><span class="right_arrow">&#8680;</span></p>
<% if (session[:cmd_id].present? && session[:cmd_id]!=0) %>

  <div class="question_mark"><span class="btn btn-xs btn-warning">&malt;</span>
    <div class="normal">
      <table border='1' class="saved_table">
        <tr>
          <th>CMD_ID</th><td class="scroller"><div><%=@base_cmds.CMD_ID%></div></td>
        </tr>
        <tr>
          <th>DESCRIPTION</th><td class="scroller"><div><%=@base_cmds.DESCRIPTION%></div></td>
        </tr>
        <tr>
          <th>SUBSYSTEM</th><td class="scroller"><div><%=@base_cmds.SUBSYSTEM%></div></td>
        </tr>
        <tr>
          <th>FORMATION_TYPE</th><td class="scroller"><div><%=@base_cmds.FORMATION_TYPE%></div></td>
        </tr>
        <tr>
          <th>CMD_TYPE</th><td class="scroller"><div><%=@base_cmds.CMD_TYPE%></div></td>
        </tr>
        <tr>
          <th>BASE_CMD_CODE</th><td class="scroller"><div><%=@base_cmds.BASE_CMD_CODE%></div></td>
        </tr>
        <tr>
          <th>BASE_CMD_MASK</th><td class="scroller"><div><%=@base_cmds.BASE_CMD_MASK%></div></td>
        </tr>
        <tr>
          <th>CRITICALITY</th><td class="scroller"><div><%=@base_cmds.CRITICALITY%></div></td>
        </tr>
        <tr>
          <th>PULSE_WIDTH</th><td class="scroller"><div><%=@base_cmds.PULSE_WIDTH%></div></td>
        </tr>
        <tr>
          <th>MAP_ID</th><td class="scroller"><div><%=@base_cmds.MAP_ID%></div></td>
        </tr>
        <tr>
          <th>UI_TYPE</th><td class="scroller"><div><%=@base_cmds.UI_TYPE%></div></td>
        </tr>
        <tr>
          <th>PREFERRABLE_DECODER</th><td class="scroller"><div><%=@base_cmds.PREFERRABLE_DECODER%></div></td>
        </tr>
        <tr>
          <th>CONFIRMATION_TYPE</th><td class="scroller"><div><%=@base_cmds.CONFIRMATION_TYPE%></div></td>
        </tr>
        <tr>
          <th>REMARKS</th><td class="scroller"><div><%=@base_cmds.REMARKS%></div></td>
        </tr> 
      </table>
    </div>
  </div>
     
<% end %>

Prototype/app/views/layouts/partials/_rails_defaults.html.erb
<meta charset='UTF-8' name="viewport" content="width=device-width, initial-scale=1.0"> <!-- To view perfectly in mobile -->
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>