Prototype/config/routes.rb
Rails.application.routes.draw do
	root "sessions#new"
	resources :subsystem_tbls do
		post :check_unique, on: :collection
		match :search, to: 'subsystem_tbls#index', via: :post, on: :collection
	end	
	resources :ui_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'ui_types_tbls#index', via: :post, on: :collection
	end
	resources :cmd_types_tbls do
		post :check_unique, on: :collection
		match :search, to: 'cmd_types_tbls#index', via: :post, on: :collection
	end
	resources :confirmation_type_tbls do
		match :search, to: 'confirmation_type_tbls#index', via: :post, on: :collection
	end
	resources :expressions do
		post :check_unique, on: :collection
		match :search, to: 'expressions#index', via: :post, on: :collection
	end
	resources :cmd_part_types_tbls do
		match :search, to: 'cmd_part_types_tbls#index', via: :post, on: :collection
	end
		
	resources :base_cmd_tbls do
		post :sub_short_name, on: :collection
		post :check_unique, on: :collection
		match :search, to: 'base_cmd_tbls#index', via: [:get, :post], on: :collection
	end
	resources :cmd_part_tbls do
		post :check_unique, on: :collection
	end
	resources :prereq_conf_expr_tbls do
		post :check_unique, on: :collection
	end
	resources :cpid_tbls do
		post :check_unique, on: :collection
	end

	resources :bit_sel_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'bit_sel_tbl_infos#index', via: :post, on: :collection
	end
	resources :bit_sel_tbls do
		post :check_unique, on: :collection
	end
	
	resources :lkup_tbls do
		post :check_unique, on: :collection
	end
	resources :lkup_tbl_infos do
		post :check_unique, on: :collection
		match :search, to: 'lkup_tbl_infos#index', via: :post, on: :collection
	end
	
	resources :users
	resources :satellite_tables
	
	resources :sessions, only: [:new, :create, :destroy] do
		post :get_db_details, on: :collection

	end
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout',  to: 'sessions#destroy'
	get  '/signup',  to: 'users#new'
  	post '/signup',  to: 'users#create'

  	get '/versions', to: "versions#index"
  	resources :versions, only: :destroy

  	resources :base_formation_logic_tbls
  	resources :map_id_tbls
  	resources :part_type_tbls
  	resources :input_format_tbls
  	resources :preferrable_decoder_tbls
  	resources :criticality_tbls
  	resources :pulse_width_tbls
  	resources :lkup_tbl_type_tbls
  	resources :logical_op_tbls

  	resources :entry_type_tbls
  	resources :value_type_tbls
  	resources :rel_op_tbls
  	resources :form_logic_part_type_tbls
  	resources :formation_logic_tbls
  	resources :form_logic_part_data_tbls do
  		post :check_unique, on: :collection
  		post :fetch_sub_logic_val, on: :collection
 	end
  	resources :expr_type_tbls
  	
end

Prototype/app/models/input_format_tbl.rb
class INPUT_FORMAT_TBL < AllConfigAccess
	self.table_name = "INPUT_FORMAT_TBL"
	has_paper_trail class_name: 'Version'
	validates :INPUT_FORMAT, presence: true, uniqueness: true
end

Prototype/app/controllers/input_format_tbls_controller.rb
class InputFormatTblsController < ParentController
	before_action :admin_user, except: :index
	before_action :set_base_cmd_session_to_nil

	def index
		@input_format = INPUT_FORMAT_TBL.all
	end

	def new
		@input_format = INPUT_FORMAT_TBL.new
	end

	def edit
		@input_format = INPUT_FORMAT_TBL.find(params[:id])
	end

	def create
		@input_format = INPUT_FORMAT_TBL.new(input_format_params)
		if @input_format.save
			flash[:success] = "Successfully created input format #{@input_format.INPUT_FORMAT}"
			redirect_to input_format_tbls_path
		else
			render 'new'
		end
	end

	def update
		@input_format = INPUT_FORMAT_TBL.find(params[:id])
		if @input_format.update_attributes(input_format_params)
			flash[:success] = "Successfully updated input format #{@input_format.INPUT_FORMAT}"
			redirect_to input_format_tbls_path
		else
			render 'edit'
		end
	end

	def destroy
		@input_format = INPUT_FORMAT_TBL.find(params[:id])
		@input_format.destroy
		flash[:warning] = "Successfully deleted input format #{@input_format.INPUT_FORMAT}"
		redirect_to input_format_tbls_path
	end

	private
		def input_format_params
			params.require(:input_format_tbl).permit(:INPUT_FORMAT)
		end
end

Prototype/app/helpers/input_format_tbls_helper.rb
module InputFormatTblsHelper
end

Prototype/app/views/input_format_tbls/edit.html.erb
<h1>EDIT INPUT_FORMAT_TBL </h1>
<div class="perfect-forms">
<%= form_for(@input_format) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="form-row">
  <%= f.label :INPUT_FORMAT %>
  <%= f.text_field :INPUT_FORMAT, class: 'form-control' %>
  </div>

  <div class="form-row">
  <%= f.submit 'Update', class: "btn btn-primary" %>
  </div>
<% end %>
</div>

Prototype/app/views/input_format_tbls/index.html.erb
<div class="table-view">
	<table>
		<caption>LIST OF INPUT_FORMATS</caption>
		<thead>
			<tr>
				<th> ID </th>
				<th> INPUT_FORMAT</th>

			</tr>
		</thead>
		<tbody>
		<% @input_format.each do |f| %>
		<tr data-href="<%= edit_input_format_tbl_path(f) %>"  class="theShower text-center">
	
		
		<td><%= f.ID  %></td>
				<td><%= f.INPUT_FORMAT %></td>
				<% if current_user.admin? %>	<!-- add this too -->
					<td class="deleter"><%= link_to "x", f , method: :delete, data: { confirm: "You sure?" } %></td>	<!-- add this too -->
				<% end %>
			
		</tr>	
		<% end %>
		</tbody>
	</table>

	</div>
<div class="lower-options add_to_right">
	<%= link_to 'Add', new_input_format_tbl_path, class: "add-new-table" %>
</div>

Prototype/app/views/input_format_tbls/new.html.erb
<h1>CREATE INPUT_FORMAT_TBL </h1>
<div class="perfect-forms">
<%= form_for(@input_format) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="form-row">
  <%= f.label :INPUT_FORMAT %>
  <%= f.text_field :INPUT_FORMAT, class: 'form-control' %>
  </div>

  <div class="form-row">
  <%= f.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>
</div>